### ISSUE TITLE
dragselect ng build error after I run npm install  on angulat 8 with typescript 3.5.3.

### ISSUE THREAD

**Issue by vineet-verma** [ThibaultJanBeyer/DragSelect#100]
I am using angular 8 version along with dragselect 2.0.2 version, Recently I am getting the error with dragselect after running npm install. Earlier( 1 week ago ) it was working fine.
I also tried with increasing dragselect version to 2.1.1, But still no luck.

+ @angular/cli@8.3.23
added 264 packages from 186 contributors in 11.428s
[32;1m$ ng build --project razor-tagging-lib[0;m
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'razor-tagging-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
WARNING: Invalid property name '' at 77:11. Ignoring.
WARNING: Invalid property name '' at 82:11. Ignoring.
WARNING: Invalid property name '' at 76:11. Ignoring.
ERROR: node_modules/dragselect/dist/modules/Area.d.ts(11,15): error TS2304: Cannot find name 'DSArea'.
node_modules/dragselect/dist/modules/Area.d.ts(65,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Area.d.ts(65,21): error TS2304: Cannot find name 'DSArea'.
node_modules/dragselect/dist/modules/Area.d.ts(70,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Area.d.ts(80,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Area.d.ts(85,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Area.d.ts(85,17): error TS2304: Cannot find name 'DSBoundingRect'.
node_modules/dragselect/dist/modules/Area.d.ts(86,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Area.d.ts(86,24): error TS2304: Cannot find name 'DSArea'.
node_modules/dragselect/dist/modules/Drag.d.ts(16,19): error TS2304: Cannot find name 'DSDragKeys'.
node_modules/dragselect/dist/modules/Drag.d.ts(83,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Drag.d.ts(83,24): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/modules/Drag.d.ts(84,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Drag.d.ts(84,24): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/modules/Interaction.d.ts(12,22): error TS2304: Cannot find name 'DSArea'.
node_modules/dragselect/dist/modules/Interaction.d.ts(42,20): error TS2304: Cannot find name 'DSEvent'.
node_modules/dragselect/dist/modules/Interaction.d.ts(48,26): error TS2304: Cannot find name 'DSEvent'.
node_modules/dragselect/dist/modules/PubSub.d.ts(11,28): error TS2304: Cannot find name 'DSCallbackNames'.
node_modules/dragselect/dist/modules/PubSub.d.ts(11,55): error TS2304: Cannot find name 'DSCallback'.
node_modules/dragselect/dist/modules/PubSub.d.ts(20,30): error TS2304: Cannot find name 'DSCallbackNames'.
node_modules/dragselect/dist/modules/PubSub.d.ts(20,58): error TS2304: Cannot find name 'DSCallback'.
node_modules/dragselect/dist/modules/PubSub.d.ts(28,26): error TS2304: Cannot find name 'DSCallbackNames'.
node_modules/dragselect/dist/modules/PubSub.d.ts(28,49): error TS2304: Cannot find name 'CallbackObject'.
node_modules/dragselect/dist/modules/SelectableSet.d.ts(14,19): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/modules/SelectableSet.d.ts(51,24): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/modules/SelectableSet.d.ts(53,27): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/modules/SelectableSet.d.ts(55,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/SelectableSet.d.ts(55,21): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/modules/SelectedSet.d.ts(24,21): error TS2304: Cannot find name 'DSElement'.
node_modules/dragselect/dist/modules/SelectedSet.d.ts(24,33): error TS2304: Cannot find name 'DSElement'.
node_modules/dragselect/dist/modules/SelectedSet.d.ts(26,24): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/modules/SelectedSet.d.ts(28,27): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/modules/SelectedSet.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/SelectedSet.d.ts(30,21): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/modules/Selection.d.ts(36,16): error TS2304: Cannot find name 'DSEvent'.
node_modules/dragselect/dist/modules/Selector.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/Selector.d.ts(32,17): error TS2304: Cannot find name 'DSBoundingRect'.
node_modules/dragselect/dist/modules/SelectorArea.d.ts(12,28): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/modules/SelectorArea.d.ts(54,25): error TS2304: Cannot find name 'DSElement'.
node_modules/dragselect/dist/modules/SelectorArea.d.ts(54,50): error TS2304: Cannot find name 'DSBoundingRect'.
node_modules/dragselect/dist/modules/SelectorArea.d.ts(60,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/modules/SelectorArea.d.ts(60,17): error TS2304: Cannot find name 'DSBoundingRect'.
node_modules/dragselect/dist/stores/KeyStore.d.ts(10,26): error TS2304: Cannot find name 'DSMultiSelectKeys'.
node_modules/dragselect/dist/stores/KeyStore.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(51,19): error TS2304: Cannot find name 'DSEvent'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(52,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(52,25): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(54,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(54,23): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(55,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(55,25): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(57,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(57,23): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(59,22): error TS2304: Cannot find name 'DSEvent'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(62,21): error TS2304: Cannot find name 'DSEvent'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(63,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(63,22): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(65,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(65,20): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(73,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(73,27): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(75,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(75,27): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/PointerStore.d.ts(77,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/PointerStore.d.ts(77,24): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(10,22): error TS2304: Cannot find name 'DSArea'.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(33,19): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(41,23): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/dragselect/dist/stores/ScrollStore.d.ts(42,23): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/DragSelect.d.ts(8,401): error TS2304: Cannot find name 'Settings'.
node_modules/dragselect/dist/DragSelect.d.ts(10,28): error TS2304: Cannot find name 'DSCallbackNames'.
node_modules/dragselect/dist/DragSelect.d.ts(11,30): error TS2304: Cannot find name 'DSCallbackNames'.
node_modules/dragselect/dist/DragSelect.d.ts(12,26): error TS2304: Cannot find name 'DSCallbackNames'.
node_modules/dragselect/dist/DragSelect.d.ts(51,25): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/DragSelect.d.ts(60,28): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(60,105): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/DragSelect.d.ts(69,31): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(69,109): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/DragSelect.d.ts(79,31): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(79,103): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/DragSelect.d.ts(88,28): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(88,105): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/DragSelect.d.ts(94,48): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/DragSelect.d.ts(101,30): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(101,74): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(106,27): error TS2304: Cannot find name 'DSElements'.
node_modules/dragselect/dist/DragSelect.d.ts(116,30): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(116,105): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(123,33): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(123,82): error TS2304: Cannot find name 'DSInputElements'.
node_modules/dragselect/dist/DragSelect.d.ts(125,37): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/DragSelect.d.ts(127,37): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/DragSelect.d.ts(129,38): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/DragSelect.d.ts(131,41): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/DragSelect.d.ts(133,41): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/DragSelect.d.ts(135,42): error TS2304: Cannot find name 'Vect2'.
node_modules/dragselect/dist/DragSelect.d.ts(141,29): error TS2304: Cannot find name 'DSEvent'.
node_modules/dragselect/dist/DragSelect.d.ts(148,73): error TS2304: Cannot find name 'Vect2'.

**Comment by ThibaultJanBeyer** [comment]
Hi @vineet-verma thanks for letting me know. Seems to be an issue with the exported types. Those names that he can't find are in types.d.ts … Looks like it's not exporting the reference to types.d.ts. I'll have a look if this can be fixed 👀

**Comment by ThibaultJanBeyer** [comment]
@vineet-verma, I think I fixed it. Unfortunately, I can't reproduce it since I've not your set-up. Can you please try the newest version `2.1.2` and let me know if that worked? Thank you!

**Comment by aldovelco** [comment]
Hello again @ThibaultJanBeyer, this is the same issue I mentioned in #93. I just wanted to let you know I updated my project to `2.2.2` and types are working as expected. Thank you once again!

**Comment by ThibaultJanBeyer** [comment]
Awesome, thanks for the feedback! 👍
