### ISSUE TITLE
Clicking on the scrollbar creates a selection

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [ThibaultJanBeyer/DragSelect#105]
**Describe the bug**
Clicking on the scrollbar creates a selection. Clicking outside of it and then dragging in scrolls the area.

**To Reproduce**
1. Open the quicktest
2. Try to scroll down

**Expected behavior**
Clicking on the scrollbar (outside of selectorarea) should not trigger a selection

**Comment by dosomder** [comment]
This issue is still present in Firefox browser, because there it seems the scrollbar is inside the scrollable area

**Comment by ThibaultJanBeyer** [comment]
Thanks @dosomder 🤗 , I just tested it in Firefox using [this pen](https://codepen.io/ThibaultJanBeyer/pen/Nvobgq) Firefox version 106.0.3 (64-bit) on MacOS and it works fine, the issue is not present. Would you mind sharing an example where the issue is still present along with the exact browser version you are using? Thank you!

**Comment by dosomder** [comment]
You're right, it's works with your codepen. I am sorry for the report. I think the theme I used (Chakra) probably modifies the scrollbar somehow, because it looks a lot thiner and with round edges.

**Comment by ThibaultJanBeyer** [comment]
Would you mind still sharing a code example with that theme? Might be interesting to look at 👀
