### ISSUE TITLE
v2 selectable items drag feature is breaking the UX | Cannot disable selectables dragging

### ISSUE THREAD

**Issue by owenfar** [ThibaultJanBeyer/DragSelect#108]
**Describe the bug**
Drag support on individual items in v2 (especially with arrow keys) is not following the common standards, and breaks everything I had from previous version. There is also no easy way (as far as I can tell from the docs) to completely disable the drag feature.

**Expected behavior**
I expect there to be a simple option inside DS object such as: `selectableDragging: false` that would completely disable all dragging related functions on all selectables - also in my opinion, dragging is not very useful without area detection and "drop" support (or am I missing this from the docs?). Can you perhaps elaborate on the purpose of this feature please?

Common/Default keyboard arrows behaviour in this case would be to select the closest item based on direction - which is something I had written custom, but now is breaking because dragSelect is dragging my items instead :/ 

**Additional context**
Please don't get me wrong, I like that the library is expanding and offering more features and options to everyone. I just personally liked that it was focused on the actual dragSelect "box" - because this is something very powerful on its own already. I also think that drag could be a separately "installable add-on package".

If there is an easy way to disable dragging entirely, please do let me know. I'll have a look at the docs again and try to figure it out from the examples provided - but so far nothing works :(

Thank you in advance.

**Comment by owenfar** [comment]
Just another note: `isDraggingKeyboard` event is not firing inside subscribe - it shows undefined - only `isDragging` event works. All I need for now is to disable all dragging features inside selectables.

**Comment by owenfar** [comment]
Sorry, I would like to ask something else here if that's ok; do we still have a way to detect the previously available `onDragStartBegin` and `onDragStart`? I was using these two functions and it was very crucial to my application the difference between these events. Is it possible to achieve the same with `subscribe`?

I hope I'm not bothering you too much about this :)

**Comment by owenfar** [comment]
Ok, I must highly apologise now - this is very weird but `keyboardDrag` was not triggering because of something stupid I did. This of course solves all the dragging issues I had with the keyboard. I was too blind and threw the blame on the library.. 
I would still wish that draggability was more detached from the main purpose of the library (Drag Select) - but that's just me.

So now my only problem is `onDragStartBegin` support. Because I used this to disable the default behaviour of deselecting all items when clicking on another item within the same group of selection.

But this is not a bug anymore, so I will close this issue.

Thank you for everything

**Comment by ThibaultJanBeyer** [comment]
I added those `onDragStartBegin` would be `predragstart` see the notes [in the docs](https://github.com/ThibaultJanBeyer/DragSelect#events):
```
Note: all your callbacks subscribers will run happen after the internal code ran. If you want to run something before everything else, use the `pre` prefix. I.e. `predragstart` is an event that runs before any internal start logic.
```
Cheers

**Comment by owenfar** [comment]
Thank you so much for reaching out @ThibaultJanBeyer :) In the end I did find it in the "Note:" section as you mentioned, but I have another problem now, this time it might actually be a bug - let me explain briefly here, and if you think so I can open another issue.

To understand this quickly, you could have a look at this example CodePen I did: https://codepen.io/owenfar/pen/LYLYPBz

Basically I had used `onDragStartBegin` in v1 to disable dragSelect when drag is coming from an "inner" element inside a selectable.

1. I'm not sure if this is the intended behaviour, because in my opinion, inner elements should behave the same as parent - try dragging item 1 from within the black border.
2. While before I could disable the default behaviour by breaking the functionality during `onDragStartBegin` (when it was coming from a child selectable element), now using `subscribe` doesn't actually teardown - even when using the stop(false,false) as suggested in the docs. This time I did a few more tests, and the problem seems to be coming from `subscribe` - `stop` doesn't remove the selected items, only the "continued" functionality of `subscribe`.

Please let me know if I was clear. What's more important from my end is to have point 2 working as it used to, because I need this for "overlay" windows over "desktop" - so that I can disable the desktop behaviour when click is coming from an overlay.

**Comment by ThibaultJanBeyer** [comment]
Your code is false. It should be `if (items.length > 0)` not `if (items.length > 1)`… `> 1` means: 2 or more items…

**Comment by owenfar** [comment]
That is just an example, so that it only triggers when more than one item is selected. The problem isn't here.

Are you still checking this or should I elaborate more regarding this issue?

The issues are as mentioned:

1. when inner elements exist in selectables - they are being ignored as part of the selectable item
2. teardown in `subscribe` still deselects selected items, even if stop(false,false) is used within

**Comment by ThibaultJanBeyer** [comment]
Ah! I think I see what you mean. Yeah looks like there is some selection going on before calling the `predragstart` when the element is not the topmost element. Without looking too much into details this seems to be a bug yeah :/ 🐞

**Comment by owenfar** [comment]
I think these are two separate bugs though, let me explain further:

Issue 1

When element is not topmost element inside selectable - normal behaviour is ignored (I suggest using [contains](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) or [closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest))

Issue 2:

Let's say you have a dragSelect area with a few items, and on the same area we have a "Copy" selected items button. Before, I used `onDragStartBegin` to stop/break functionality (as I need to copy _and_ keep the selection). But now with `predragstart` this doesn't work anymore, as it's deselecting the items, even if I use stop(false,false) or break() - you can check in the example provided, when you select more than one item - clicking outside should not deselect them.

Sorry that I wasn't clear about explaining them as separate issues before, they are related for one use case, but are separately causing problems in my environment for other use-cases.

...

What do you think about issue 2 - is there a workaround for this?

**Comment by owenfar** [comment]
Eventually I would suggest having something like `ignore: ".class-name"` property when creating a new DragSelect object? I think that this would be very useful for when we have elements placed above the same dragSelect area we want to ignore - but for now I still think solving issues 1 & 2 would make the library more robust as it is.

I would like to help solve these issue if you don't have time, but I would love some direction as I'm not familiar at all with this codebase. Thank you

**Comment by ThibaultJanBeyer** [comment]
Hi yeah I'm on holidays for the next weeks, maybe I find some time to look into this. I still don't quite understand all the points you wrote to be honest. What would help maybe is if you could create a screen recording where you explain what you mean?

Generally yes, please contribute and help! What would you need to know?

**Comment by ThibaultJanBeyer** [comment]
and feel free to open a new issue

**Comment by owenfar** [comment]
Will open separate issues and explain in detail with video so that it's crystal clear :) Thanks, and enjoy the holidays!
