### ISSUE TITLE
Inner elements are being ignored as part of the selectable item

### ISSUE THREAD

**Issue by owenfar** [ThibaultJanBeyer/DragSelect#109]
**Describe the bug**
When element is not topmost element inside a selectable - normal behaviour is ignored (if possible I suggest using [contains](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) or [closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) - depends on what current methods are being used).

**To Reproduce**
See: https://codepen.io/owenfar/pen/LYLYPBz

Try dragging item 1 from within the black border.

**Expected behavior**
When clicking or dragging on an "inner" element of a selectable item, it should be treated same as the "parent" selectable element (here I mention clicking because if all items are selected and we click on item 1 from within the black border, the rest are also deselected - they should not)

**Additional context**
dragSelect version 2.2.2

**Comment by ThibaultJanBeyer** [comment]
Hi @owenfar, thanks again for reporting this! Looks like a bug indeed! Do you wanna have a try at this one? Or want me to take a look? PS: Merry Christmas to you =)

**Comment by owenfar** [comment]
Hello @ThibaultJanBeyer , really happy to see you working on previous fixes. Thank you so much for your time. 

It's crazy times for me with external projects at the moment. Honestly I don't see myself having a look until around February, when things re-adjust.. but I would love to dedicate some time to get used to this code-base and wish to spare more time on helping out here.

Merry Christmas to you too, and thanks again for the updates, I will now be able to upgrade to latest version :)

**Comment by ThibaultJanBeyer** [comment]
This was an easy one, PR is out :)

**Comment by owenfar** [comment]
That's a pity :) Annoying when something that seemed simple turns out to be a pain ... Hopefully you'll figure it out. Otherwise I will definitely jump in to help soon. Thanks!

**Comment by calebwaldner** [comment]
Love this package! I am having some trouble with this issue too. 

I found a workaround by making my draggable div with no children pass its transform style to another identical div directly under it that has all the children on the 'dragmove' event. Seems to work good. 

I'll keep a watch on this issue for a fix. Again, love the package, exactly what I needed; works great!

**Comment by ThibaultJanBeyer** [comment]
fixed in [v2.3.1](https://github.com/ThibaultJanBeyer/DragSelect/releases/tag/v2.3.1) 🥂
