### ISSUE TITLE
Teardown inside predragstart event still deselects items

### ISSUE THREAD

**Issue by owenfar** [ThibaultJanBeyer/DragSelect#110]
**Describe the bug**
If we have a group of selected items, it's not possible to "break" or "pause" dragSelect without deselecting the items inside `predragstart` event. 

To be completely honest, I'm not sure if this is a bug or a missing feature - but if we compare the behaviour with what we used to have as `onDragStartBegin`, then it is - at least for me it breaks the expected behaviour. 

The main issue is that if we want to stop dragSelect from continuing inside a `predragstart`, it's not possible anymore without deselecting any selected items. I think to understand this better you'll have to see the example I prepared below:

**To Reproduce**
See: https://codepen.io/owenfar/pen/yLXyxZj?editors=1111

Try selecting any of the items and click on "Copy selected items". As you can see, inside `predragstart` we have a condition that when met, should stop/pause functionality. I used this before to "ignore" dragSelect on certain items within the "draggable" area.

**Expected behavior**
`predragstart` should leave and allow any selected items at the end of event when break() or stop(false,false) are present.

**Additional context**
dragSelect version 2.2.2

**Comment by ThibaultJanBeyer** [comment]
Yes, this looks like a bug. I'm on it 💪

**Comment by ThibaultJanBeyer** [comment]
Update, I found the issue but it will take a bit longer to fix and now it's Christmas 🎄 🎅  thanks for your patience =)

**Comment by ThibaultJanBeyer** [comment]
found some time and pushed the fix. It's in 2.3.0. Both, `break` and `stop` will now work. I'd recommend going with `stop` & `setTimeout(start)`
