### ISSUE TITLE
How click on a element inside the selectables area without trigger a select ?

### ISSUE THREAD

**Issue by taha-azzabi** [ThibaultJanBeyer/DragSelect#113]
Hello

Please i wonder if there a way to click in a button inside a selectables area without trigger a select ? please see the above picture.

![__picture](https://user-images.githubusercontent.com/1032609/138162636-572f2d07-912d-4d56-ab03-92e5b2bff67e.png)

Thank you

**Comment by wisp-x** [comment]
I have the same problem.

**Comment by ThibaultJanBeyer** [comment]
Hi @taha-azzabi & @wisp-x thanks a lot for using the tool <3

You can use `.break()` for that. I.e.
```
ds.subscribe('predragstart', ({ event }) => 
             event.target.className.includes('inner') 
             ? ds.break()
             : null
)
```
[See it in action](https://codepen.io/ThibaultJanBeyer/pen/ZEXaBKb)
