### ISSUE TITLE
Is there any way to disable 'dragselect' on mobile devices.

### ISSUE THREAD

**Issue by wisp-x** [ThibaultJanBeyer/DragSelect#118]
thanks for the great lib!

**Is your feature request related to a problem? Please describe.**
Dragging to select an item is not a good experience on mobile devices

**Describe the solution you'd like**
On the mobile device, I want to close 'dragselect' and select items by clicking.

**Describe alternatives you've considered**

I tried to judge whether it is necessary to disable 'dragselect' by judging whether it is currently accessed by a mobile device, but hope there is a better solution. It would be better if an API is provided inside the plug-in.

**Additional context**
dragSelect version 2.3.0

**Comment by ThibaultJanBeyer** [comment]
Hi there wisp-x! Thanks for using the lib ❤️ 
I don't really understand what you're trying to explain, would you be so kind to upload a screen capture maybe?
Because you should be able to select items by tapping with your finger as well, yes
Thank you

**Comment by wisp-x** [comment]
thanks for your positive response!
Simply put, I want to disable ‘dragselect’ on mobile devices. Here is my current solution:
```javascript
// ...
const ds = new DragSelect({
    area: document.getElementById('container'),
    keyboardDrag: false,
});
ds.subscribe('predragstart', ({ event }) => {
    if (isMobile()) {
        ds.stop();
    }
});

// ....
```
But I’m thinking, is it possible to provide this method inside ‘dragselect’？

**Comment by ThibaultJanBeyer** [comment]
Why not simply?
```JavaScript
let ds
if(!isMobile()) {
  ds = new DragSelect({ ... });
  ...
}
```
