### ISSUE TITLE
Can I add selectable element when I dragging in a area?

### ISSUE THREAD

**Issue by Tz-george** [ThibaultJanBeyer/DragSelect#119]
**Describe the bug**
I have a updating list container, when I scroll down, this list will updating data. If I select with dragging, and I drag to edge of bottom, I update data to this list. These new data can't be selected in dragging. Only selectable when I stop dragging and add selectable to dragSelect object. How to add selectable element when I dragging scroll.

**To Reproduce**
1. new a dragSelect object with scroll area and selectable element
2. set area update when it scroll to bottom
3. set dragSelect subscribe 'Interaction:update' or 'Area:scroll' or 'dragmove', and callback addSelectable same element.
4. drag to select
5. update element when drag to bottom, this new element cannot be selected.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: latest

**Additional context**

**Comment by ThibaultJanBeyer** [comment]
Hi @Tz-george thanks for using the tool 🤗 
can you please add a code example?
You can use codepen for it, [here is an example](https://codepen.io/ThibaultJanBeyer/pen/Nvobgq) that you can copy :)
Thank you!

**Comment by ThibaultJanBeyer** [comment]
Hi @Tz-george I am closing this since I don’t really understand what you mean and did not hear back from you since last year. Feel free to re-open and provide more details, a recording would be good here I think. Thank you!
