### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by Gruxme** [ThibaultJanBeyer/DragSelect#127]
A vue 3 package would be much appreciated

**Comment by ThibaultJanBeyer** [comment]
Hi Gruxme, thanks for using the tool.
Any version of Vue or whatever library is supported by default since this tool is written in vanillajs.
Cheers

**Comment by xlmnxp** [comment]
@ThibaultJanBeyer I tried it today and it don't work with Vue

**Comment by ThibaultJanBeyer** [comment]
Would you be so kind to share a code example of what you tried? Thank you
