### ISSUE TITLE
Min distance to be considered a select

### ISSUE THREAD

**Issue by Yixn** [ThibaultJanBeyer/DragSelect#130]
I would like to set a min distance before it actually starts the selecting rectangle

**Comment by ThibaultJanBeyer** [comment]
Hi @Yixn would you mind elaborating what exactly you mean please? Thank you 🤗

**Comment by ThibaultJanBeyer** [comment]
I’m closing this since I did not hear back from you @Yixn and am not sure if I understand what you mean correctly. Feel free to re-open with a more precise description of your feature request :)
