### ISSUE TITLE
Drag select libaray 2.3.1 not capturing multiple items with angular 9 version

### ISSUE THREAD

**Issue by gauravdhmj** [ThibaultJanBeyer/DragSelect#134]
Drag select libaray 2.3.1 not capturing multiple items with angular 9 version
**Describe the bug**
When user drag mouse on multiple words, It does not capture any word.

**Expected behavior**
Program should return the selected words on the browser.

**Code Example**
We are using below code in our application to create a drag select library object.

this.ds = new DragSelect({
  selector: document.getElementById('rectangle'),
  selectables: document.getElementsByTagName('rect') as unknown as SVGElement[],
  //multiSelectKeys: ['ctrlKey', 'shiftKey'],
  area: document.getElementById('images'),
  draggability: false
});
this.ds.start();

and 

We are trying to retrieve selected element using below code.
let element = this.ds.getSelection();
element variable length is always zero while we select more than one word.However, it works fine with single selection

**Screenshots**

In the screenshot, we have selected 2 words("AS PER") using mouse drag(they are visible with dotted rectangle) on chrome browser. However, Drag select library not able to capture selected words using "getSelection()" method because we have selected multiple words.

![Error_DragSelect](https://user-images.githubusercontent.com/16702536/182132599-fced0e0d-d37e-4de2-9097-503962fc5af3.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise and centOS
 - Browser: chrome
 - OS Build Version: 19044.1826

**Additional context**
Our Application is using angular 9.

**Comment by ThibaultJanBeyer** [comment]
Hi @gauravdhmj thanks for using the tool! ❤️‍🔥 

I am trying to reproduce your issue, are you able to share a https://codepen.io/pen/ by any chance? You can use [this one](https://codepen.io/ThibaultJanBeyer/pen/prpwYG) as a starting point. Theoretically, it should not be related to Angular. This would make it easier for me to reproduce.

Thank you!

**Comment by ThibaultJanBeyer** [comment]
Ideally would be nice to have a [guide for Angular as mentioned here](https://github.com/ThibaultJanBeyer/DragSelect/issues/141#issuecomment-1326811931). Without a code example, unfortunately, I can’t help. I’ll close it for now and have a look into Angular. Please provide a code example and feel free to re-open if you have one.
