### ISSUE TITLE
DragSelect `removeSelectabes(node, true)` is not permanent

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [ThibaultJanBeyer/DragSelect#148]
**Describe the bug**
DragSelect `removeSelectabes` is not permanent. After applying it, it would re-add the element on the next iteration. Probably has to do with the settings store.

**To Reproduce**
1. Select the element
2. Add a callback listener and remove the item from the selectables with ` ds.removeSelectables(item, true)`
3. Select anything else, then drag another selection => the item is re-added to the selectables

**Expected behavior**
Once removed it should not be part of the selectable items anymore

**Code Example**
https://codepen.io/ThibaultJanBeyer/pen/oNyWpwQ

**Comment by clementrcheng** [comment]
First of all, thanks for the library!

In case anybody else is also having this issue, here's how I'm getting around it. 
(Not sure if this might have any side effects but at least it's working)

// initial setup
const ds = new DragSelect({
  selectables: document.querySelectorAll('.draggable'),
});

// when you're calling 'ds.removeSelectables(item, true)', also do this:
item.classList.remove('draggable');

// then update the settings
ds.setSettings({
    selectables: document.querySelectorAll('.draggable'),
  });

@ThibaultJanBeyer - just out of curiosity, are there any plans of fixing this in an upcoming release? Thanks again!

**Comment by ThibaultJanBeyer** [comment]
Hi @clementrcheng awesome! Thanks for the workaround, of course it’s planned to fix all bugs =) thanks for your patience

**Comment by ThibaultJanBeyer** [comment]
This is fixed in [v3](https://github.com/ThibaultJanBeyer/DragSelect/pull/200) which is coming soon :)
