### ISSUE TITLE
Adding Unit Test

### ISSUE THREAD

**Issue by RealTJ** [ThibaultJanBeyer/DragSelect#15]
Hey i thought about adding Unit Test before trying to debug more issues or bringing the Software forward.
I think it would help out to describe the intended behavior, of new functionality. That in turn makes it easier to communicate, what we wish to do (e.g. you could write a unit test that i could fulfill, or i could write a unit test which describes a bug etc.). 

I researched a little bit and stumbled on this link: [Overview of Javascript testing in 2018](https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2018-f68950900bc3)

I have some experince in Jest and also tried puppeteer for a while. I would like to implement a solution with that, but i want to know if you have any favorites or plans for Unit testing?

**Comment by ThibaultJanBeyer** [comment]
Yes, tests would be amazing. This is something that would really help. 

I think Functional tests would also be very very useful, however, the difficulty is on how to mock mouse dragging.

From the frameworks I used so far, my favourite was puppeteer. The only downside is, afaik, you can only test chrome, no other browsers. Or am I wrong?

You’re welcome to implement the testing strategy to your likings. Try to keep it simple tho’
Thanks for the link, it is **very** insightful!

**Comment by RealTJ** [comment]
Yes mouse movement can only simulated (as far as i know) in puppeteer which is an wrapper for chrome headless. It seems that Firefox has also a headless mode, but there are no wrapper libraries for it yet. This would make it easy to have an API that abstracts both puppeteer and Firefox. 

What i would suggest is that we implement the functional test with Jest/Puppeteer and look what 2018 does for Firefox headless testing and if it looks good implement that too.

> You’re welcome to implement the testing strategy to your likings. Try to keep it simple tho’

I will look try it out and make a pull request as always. In the beginning i will only test the simplest of things, which we can build upon to have better testing.

**Comment by ThibaultJanBeyer** [comment]
Sounds great, looking forward for this :)

**Comment by RealTJ** [comment]
Short update on this, i needed to replace the jshint package with eslint since jshint does not really support `async`/`await` but that is heavily needed to make the testing code with puppeteer look sane. 

I based my decision mostly on this thread:
[Experimental Traceur features/ES7](https://github.com/jshint/jshint/issues/1939)

I used a tool called [polyjuice](https://github.com/brenolf/polyjuice) to convert the jshint to eslint. So far it worked fine. But i would like to hear your input on it, does anything speak against this decision?

**Comment by RealTJ** [comment]
No Problem, i was very busy the last two weeks, so i'm not so as far as i want to. 

I managed to make one simple test, where i check if all the callbacks get called.
I'm not happy yet how the folder structure is, since i now have two test folder, one for the html tests `tests` and one for the actual jest tests `__tests__`.

The setup is actually pretty simple: I have a Webserver which provides an interface for the `testx.html` and then i run the jest tests. Where `test0.js` corresponds to `test0.html`.

Some tests get a little bit trickier to do, since you have to check the absence of the rectangle, right now i would say the only way you can do it by comparing a picture? But i think that is a bit advanced.

Furthermore i don't see any use for traditional unit tests right now since everything is really depended on mouse movement / keyboard input for it to work. This is very hard to mock / emulate. The only thing you could reliably test is if the Object gets initialized correctly, but i don't think that is of much use. 

Should i make a pull request?

**Comment by ThibaultJanBeyer** [comment]
Yes, that is what I was saying, mocking the mouse and dragging and stuff is unfortunately extremely difficult :( … It would be nice to be able to get rid of the html manual tests and use automated ones, but not sure if that is even feasible with todays technology.

Sure, you’re welcome to make a PR

**Comment by RealTJ** [comment]
Ok, it is not finished as of yet, but maybe you can look at it and see where it goes and give some feedback.

**Comment by ThibaultJanBeyer** [comment]
There is still a lot to do since the tests do not really cover a lot yet. However, I think you made a good starting point.

I’ll close this issue but that does not mean that we are done „adding Tests” which should be done on every change.

Then, once there is a good code coverage, having a look at a continuous integration workflow might also make sense.

Thanks again for raising this valid feature request and for helping to implement it with your PR, that helps a lot! Thank you 💯
