### ISSUE TITLE
Have a trouble with click, double click event

### ISSUE THREAD

**Issue by iceleo-com** [ThibaultJanBeyer/DragSelect#16]
I can not bind the click event on the items (selectable items) in "area" element. I think the code will be stopped immediately, so it can not fire the event.

**Comment by ThibaultJanBeyer** [comment]
Hi iceleo-com,

thanks for using the tool!
Unfortunately, I don’t really understand your issue. Would you mind adding some code of what you are trying to do? And maybe explain in more detail. Feel free to use one of the [codepens](https://codepen.io/ThibaultJanBeyer/pen/prpwYG).

Thank you.

**Comment by iceleo-com** [comment]
Hi,

Yesterday, I had a issue with click event. But today, it works well, the code is same. I have create a sample code in codepens [https://codepen.io/iceleo/pen/Yapbqr](https://codepen.io/iceleo/pen/Yapbqr) to describe my code.

Thankyou.

**Comment by ThibaultJanBeyer** [comment]
I can’t reproduce.

When I doubleclick, then the text get’s selected, yes. But that is a normal browser behaviour. Try double or trippleclicking this text for instance, the browser will select the word or the paragraph.
To turn this behaviour off, you can add `user-select: none` in your CSS. Don’t forget to add the Mozilla, Microsoft and Webkit specific prefixes (you forgot those in your example code).

See https://developer.mozilla.org/en-US/docs/Web/CSS/user-select.
