### ISSUE TITLE
Not working after restarting

### ISSUE THREAD

**Issue by sahithyandev** [ThibaultJanBeyer/DragSelect#170]
**Describe the bug**
DragSelect is working normally. But it stops working after calling `.stop()` and `.start()` (restarting). The selection area is not showing after that.

**To Reproduce**
1. Initialize a `DragSelect` instance (as `ds`).
2. Call `ds.stop()`
3. Call `ds.start()` after a time interval (or immediately)
4. Try selecting

**Expected behavior**
Work as expected after restarting.

**Code Example**
Basic reproduction on CodePen: https://codepen.io/sahith27/pen/dyqvPmQ
I have added few lines of code into the demo from homepage.

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 
   - Google Chrome: 110.0.5481.178 (Official Build) (64-bit) (cohort: Stable) 

I have skipped out the Smartphone section as I haven't tested on them. I hope it isn't necessary. Let me know if additional info is needed for this issue.

**Comment by ThibaultJanBeyer** [comment]
Hi @sahithyandev thanks for using the tool and thanks for reporting the bug. I fixed it in version `2.7.2`. Cheers 🥂
