### ISSUE TITLE
Releases starting with 2.4.0 cause typescript errors 

### ISSUE THREAD

**Issue by Brian-Hofmann** [ThibaultJanBeyer/DragSelect#175]
I just updated my DragSelect version from 2.3.1 to the latest (2.7.3 as of right now). When I ran my project, I now receive typescript errors relating to the SelectableSet and SelectedSet classes. I confirmed that this is an issue starting with 2.4.0. I am running this in an Angular app with typescript version 4.6.3. If there is anything on my side I am missing, please let me know. Thank you!

Screenshots:

![image](https://user-images.githubusercontent.com/37916393/225195902-1a992294-c7d3-4eb3-9fbc-85fd246140d7.png)
![image](https://user-images.githubusercontent.com/37916393/225196035-bedab84a-4957-4eb0-8094-e20bbdaf911d.png)

**Comment by ssergdev** [comment]
+1

**Comment by ThibaultJanBeyer** [comment]
Hi there, thanks for pointing this out! Would you mind sharing an example code/project that reproduces this error?
Just FYI I’m also working on a typescript rewrite of the project but this will take some more time, would be good to get this fixed before.

**Comment by Ruslan207** [comment]
i investigated the issue. `add()` signature should be changed in `SelectedSet.d.ts` and `SelectableSet.d.ts`
it should be `add(element: DSElement): this;`

**Comment by ThibaultJanBeyer** [comment]
Ok that is simple enough! Will fix that quickly. I’ve been working on a complete typescript rewrite and it should come in 1-2 weeks also. But let me quickly fix this then :)

**Comment by ThibaultJanBeyer** [comment]
Fixed in https://github.com/ThibaultJanBeyer/DragSelect/commit/87254fd75ebcb2e1a9e9fedb4ab014cd24e83ccc.
Please let me know if not.
Thanks @Ruslan207, feel free to just issue PRs next time :)

**Comment by Brian-Hofmann** [comment]
Thank you! I will try this and let you know

**Comment by Brian-Hofmann** [comment]
Works good! Thanks!
