### ISSUE TITLE
Weird behaviour when selectable items are disabled

### ISSUE THREAD

**Issue by free-easy** [ThibaultJanBeyer/DragSelect#18]
Hi,

first and foremost, thank you for this awesome library!

I've just noticed a weird behaviour:
when the selectable items are disabled sometimes there are lags when selecting them.

Browser: Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
Here the [codepen](https://codepen.io/free-easy/pen/KoXavG).

**Comment by free-easy** [comment]
Hey, thanks for your explanation.
By digging more into the problem I found out that there was no lag at all.
Simply, it seems that the `mouseover` (or something like this) event isn't available as well on disabled elements. Thus when I dragged quickly over the elements it seemed to be an instant of lag.

I'll redesign my app and avoid to use disabled element.

Thank you very much again!

**Comment by ThibaultJanBeyer** [comment]
Ah yes, I see, thanks for the gif! It makes sense.
Indeed it seems to be a chrome specific issue where it stops propagation on disabled elements as it works fine in FF for example. As it seems to be a browser specific thing, I don’t think there is much I could do about it, unfortunately… Better try to avoid disabled elements.
Feel free to report any other issue/solution you come across.
