### ISSUE TITLE
Bug on Auto Complete

### ISSUE THREAD

**Issue by DonWolfram** [ThibaultJanBeyer/DragSelect#181]
When using the browsers auto complete functionality on an input, the following bug occurs
in `Keystore.js` `keyup` and `keydown` events:

TypeError: Cannot read properties of undefined (reading 'toLowerCase')

**Code Example**
https://codepen.io/woelfners-miracles/pen/ExdLpEo

**To Reproduce**
1. Enter something in the input
2. Submit the form
3. (Refresh the page, because of the 404 Error caused by the form action)
4. Click on the input and select something from the suggestions
5. Have a look at the console to see the error

Thanks for the help and the great work on Dragselect! Keep it up!

**Comment by ThibaultJanBeyer** [comment]
Thank you DonWolfram, this is an easy fix and I’ll include it in the refactor PR coming soon https://github.com/ThibaultJanBeyer/DragSelect/pull/174

**Comment by scgm11** [comment]
any update on this? thanks!

**Comment by bedirhangull** [comment]
same problem

**Comment by bedirhangull** [comment]
@DonWolfram  did you fix this problem?

**Comment by bedirhangull** [comment]
I fixed this problem in input element. If you rewrite input element like this:               
```
<input
                readOnly={readOnly}
                onFocus={() => setReadOnly(false)}
                onBlur={() => setReadOnly(true)}
                autoComplete="off" // AutoComplete devre dışı
                autoCorrect="off" // AutoCorrect devre dışı (isteğe bağlı)
                autoCapitalize="none" // AutoCapitalization devre dışı (isteğe bağlı)
                spellCheck="false"
                name='email'
                onChange={handleChange}
                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:shadow-sm w-full p-2.5"
                placeholder="example@domain.com"
                required
              />
```
it will be fix

**Comment by ThibaultJanBeyer** [comment]
Will be fixed in [v3](https://github.com/ThibaultJanBeyer/DragSelect/pull/200) which will be out very soon :)
