### ISSUE TITLE
Area ts type

### ISSUE THREAD

**Issue by eddie-englund** [ThibaultJanBeyer/DragSelect#184]
**Describe the bug**
The type of "area" is:

```ts
type area = Document | HTMLElement | SVGElement | undefined;
```

It should also have `null` in the union type because document.getElementById's type is:

```ts
type elById = HTMLElement | null;
 ```

**To Reproduce**
Install the package and add an area like in the docs: https://dragselect.com/docs/guided-examples/Area
**Expected behavior**
It should not throw a type error.

**Screenshots**
![image](https://github.com/ThibaultJanBeyer/DragSelect/assets/16852656/19ba4c15-73a6-4b57-9f34-4df4f623678f)

- Version 2.7.4

**Comment by ThibaultJanBeyer** [comment]
Thank you, will add it to the typescript rewrite https://github.com/ThibaultJanBeyer/DragSelect/pull/174. If you know that the element you are selecting is always available, it makes sense to use `!` or `as HTMLElement`.
