### ISSUE TITLE
How to maintain the selection order 

### ISSUE THREAD

**Issue by EABangalore** [ThibaultJanBeyer/DragSelect#187]
Hi i want to maintain the selection order for when i do

ds.getSelection();  // i must get those element based on their selection 

for example :

if i select   3, 2 , 1  them i must get   `ds.getSelection(); `  // 3,2,1  not `ds.getSelection();` // 1,2,3

**Comment by ThibaultJanBeyer** [comment]
Hi @EABangalore thanks for using the tool 💪 I’ll close this since it is not an issue, but rather a question for the [discussions](https://github.com/ThibaultJanBeyer/DragSelect/discussions) I assume. How about sorting the selection?
