### ISSUE TITLE
mouse position change when you drag element in scrollable area

### ISSUE THREAD

**Issue by EsamR** [ThibaultJanBeyer/DragSelect#188]
in the documentation here https://dragselect.com/docs/guided-examples/Area to be specific 
notice that when you drag the element to the edge of the scrollable element the position of the mouse changes and never go back to the origin position if you moved the opposite side

**Comment by ThibaultJanBeyer** [comment]
Hi @EsamR thanks for reading through the docs 😍 … However, I am not able to reproduce what you are describing. The best would be if you could share a recording. But it does not sound as if it would have anything to do with the library
