### ISSUE TITLE
No way to disable drag select

### ISSUE THREAD

**Issue by barelyconfused** [ThibaultJanBeyer/DragSelect#194]
Sometimes it is necessary to disable drag selection, for example, when clicking on certain elements in the container.  In Jquery selectable, there is a way to cancel and filter out certain elements. Need something similar.

**Comment by barelyconfused** [comment]
Thanks for responding. I went through the docs and must've missed that section. However, using start/stop isn't helpful in my case since stop unbinds all the "selectables" so that when start is called again, i can no longer select the items. It requires the page to be reinitialized. I have used a workaround in my case by setting the drag area to an empty div when i need to disable it.

**Comment by ThibaultJanBeyer** [comment]
Hey @barelyconfused, what you are describing would be a bug. Which version are you on? On the latest version (3.0.3) I was not able to reproduce what you are writing. I stop and after 8 seconds I do start and it works perfectly without "unbinding" the selectable. If you are use 3.0.3 can you please share a code example? You can use this one as a playground: https://codepen.io/ThibaultJanBeyer/pen/PoXdPYG
