### ISSUE TITLE
Issues with event handlers

### ISSUE THREAD

**Issue by barelyconfused** [ThibaultJanBeyer/DragSelect#195]
"ElementSelect" is fired when user releases mouse (pointer up). It should happen during drag selection. This is doing the same as "callback" event.

"ElementUnselect" is still fired after user releases mouse (callback event has already been called). Event should not be called

**Comment by ThibaultJanBeyer** [comment]
Hey there again, I am not sure what you are describing but I’ve reworked the events in the [v3](https://github.com/ThibaultJanBeyer/DragSelect/pull/200) so it should make more sense there, it’s coming soon! Closing this for now 👋
