### ISSUE TITLE
When the drag time is over, how do I get the element back to its original position

### ISSUE THREAD

**Issue by sunjiesama** [ThibaultJanBeyer/DragSelect#196]
When the mouse drag is over, I want to return the selected element to its original position, I did not find a solution to this problem in the document, what should I do

**Comment by ThibaultJanBeyer** [comment]
Hi there @sunjiesama and thanks for using the tool, what you are describing is not an issue, it’s rather a question to ask in the [discussions](https://github.com/ThibaultJanBeyer/DragSelect/discussions) tab. You could save the original positions in a variable on start and then reset them on stop. Cheers 🥂
