### ISSUE TITLE
Make possible to attach extra data to selectable items

### ISSUE THREAD

**Issue by basharov** [ThibaultJanBeyer/DragSelect#197]
**Is your feature request related to a problem? Please describe.**
When I run some logic inside 'callback' event, it would be great to have not only the DOM element itself, but also some additional data I assign somehow before. For example, I have 100 items in an array which have their IDs from DB for each. Now I map them in the UI to the UI elements. When I get a selection, I'd like to see the IDs, not only the DOM elements.

**Describe the solution you'd like**
It would be nice to be able to attach some extra data to every element when they are added via `.addSelectables()`.

**Comment by ThibaultJanBeyer** [comment]
Hi @basharov thank you for the feature request! I don’t think this is something that should live in the library as it should not be used as a data store. There is multiple ways to overcome this without changing the library: One idea would be to add that extra information to the html element itself [using data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes). Another option would be to keep that information in your code in a map i.e. `new Map([[element, {…extraInformation}]])` and then later just `map.get(element)`. Cheers 🥂
