### ISSUE TITLE
Disable Draggability in React

### ISSUE THREAD

**Issue by praveenrajsr** [ThibaultJanBeyer/DragSelect#198]
**Disable the draggability bypassing the settings prop**

```
<DragSelectProvider settings={{ draggability: false }}>
{
    data.map((item: any) => <CompactFolderDetail key={item.id} className='mt-10 lg:mx-5 md:mx-2 mx-2' name={item.name} created=" 2 days ago" />)
}
</DragSelectProvider>
```

**Expected behavior**
The above code has to disable the dragging feature of each child element. But it's not working as expected.

**Comment by ThibaultJanBeyer** [comment]
Hi @praveenrajsr and thanks for using the tool, unfortunately I don’t understand what you mean, would you be so kind to provide a code example to reproduce the issue and maybe a recording of what you mean? I’ll close the issue until then, feel free to re-open once provided. Thank you 🤗
