### ISSUE TITLE
Clicking on an empty space in the area will cause pixel offset

### ISSUE THREAD

**Issue by Hweiya** [ThibaultJanBeyer/DragSelect#208]
**Describe the bug**
Clicking on an empty space in the area will cause pixel offset

**To Reproduce**
1. Create a project to import the dragselect component
2. Write the area property, giving a specific width and height and overflow:auto
3. Click on the empty space in the area
4. When there are enough child elements to support the height, it is obvious that the scroll bar has been rolled down some distance, which is not the desired effect

**Expected behavior**
I want it to stay still

**Code Example**
![1696752089515](https://github.com/ThibaultJanBeyer/DragSelect/assets/100832941/25c8df30-71e9-45fb-bba9-d96dcd6d6f17)

**Screenshots**
![1696752009026](https://github.com/ThibaultJanBeyer/DragSelect/assets/100832941/8c30bd40-d125-4055-b188-ca45d9e67b05)

**Desktop (please complete the following information):**
 - OS: window
 - Browser chrome
 - Version dragselect": "^2.7.4"

**Additional context**

**Comment by dbougan** [comment]
@Hweiya @ThibaultJanBeyer 
I ran into this issue as well and think I found out what is causing it. The canScroll method seems to manually adjust the scrollTop property of the drag area to check if it is scrollable: https://github.com/ThibaultJanBeyer/DragSelect/blob/main/DragSelect/src/methods/canScroll.ts#L13-L18

I don't know enough to say if that's the best way to verify scrollability, but I think we could implement the simple change shown in this diff. It performs the same operation, but restores the scrollTop property to it's original value before the DOM is updated.

![image](https://github.com/ThibaultJanBeyer/DragSelect/assets/11504841/538793f2-96f9-4a51-9d95-c315e46366d4)

**Comment by ThibaultJanBeyer** [comment]
Hey everyone, thanks for using the tool!!  @dbougan, feel free to issue a PR with your proposal and we get it merged as a workaround and add a @todo "find a better way to test scrollability". This gives us time to figure out if there is not a better way to test it. Unless you also feel like researching this immediately of course.
Thanks again for looking into this and providing a working alternative 😊

**Comment by dbougan** [comment]
Hey @ThibaultJanBeyer, I created a new Pull Request #210 with this change and a new test case to cover it
Thanks for your responsiveness, and please let me know if you would like anything changed in the PR

**Comment by ThibaultJanBeyer** [comment]
Fixed in 3.0.4

**Comment by dbougan** [comment]
I'm happy to help out @ThibaultJanBeyer, thanks for pulling it in!

Also, I'm sorry to see about the test failure I caused. Apparently, during development, I was running yarn in a way that only ran tests related to my code changes. I see the correct way to run all tests now and will do that going forward. But thank you for sorting out the Settings tests!
