### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Ruslan207** [ThibaultJanBeyer/DragSelect#212]
**Describe the bug**
when i install and import DragSelect v3.03 or v3.0.4, it throws typing error
Error: node_modules/dragselect/dist/DragSelect.d.ts:767:40 - error TS2304: Cannot find name ‘E_1’.
767     publish: <T extends DSCallbackName<E_1>>(eventName: T | T[], data: DSPublishMappings<E>[T]) => void;

I've checked `DragSelect.d.ts` in `dist` folder and `E_1` is mentioned there only once

**Comment by kkkheladze** [comment]
Having the same problem... Settled down for v2.7.4

**Comment by ThibaultJanBeyer** [comment]
Hi there @Ruslan207 thanks a lot for reporting! I'm looking into this at the moment. Would you mind sharing how you are building it? Like what's your environment? And ideally a sandbox that reproduces the error?

**Comment by ThibaultJanBeyer** [comment]
I tried with a nextjs app and it builds fine. However the line you mentioned seems weird indeed. I'll have a look on what generates that line. If you experience this issue but want to use v3 you can rename `E_1` to `E` for now.

**Comment by ThibaultJanBeyer** [comment]
I think I got it, [PR is out](https://github.com/ThibaultJanBeyer/DragSelect/pull/214)

**Comment by ThibaultJanBeyer** [comment]
It should be fixed now, please re-try and let me know :)
