### ISSUE TITLE
Touch issues due to default behavior of `touchstart` prevented

### ISSUE THREAD

**Issue by khang-nd** [ThibaultJanBeyer/DragSelect#223]
Hi, thanks for a great library, I'm using it in production for one of my apps and have purchased a license to support the development 😇

I'm reporting an issue that the following line of code is causing several issues in my app on touch devices:

https://github.com/ThibaultJanBeyer/DragSelect/blob/4dfbd56d94c9f354994b5e0a3c7e5bd1efe6970a/DragSelect/src/modules/Interaction.ts#L104

I would suggest looking for alternatives to prevent double click, preventing the touchstart's default behavior altogether seems to be an overkill and has been seen causing issues.

**Comment by ThibaultJanBeyer** [comment]
Hi thanks a lot @khang-nd for both, reporting this and supporting the project ❤️ 
Would you mind sharing a simple code example that breaks because of the preventDefault? This would make it way easier to solve and find an alternative! Thank you :)

**Comment by khang-nd** [comment]
Hi @ThibaultJanBeyer, unfortunately, I don't really have the time to set up a simple repro to assist with this issue. For my case, I just used `patch-package` and made the necessary change, and it appears sufficient. Feel free to ignore this issue and if in the future, there's a similar request, you can always revisit it 🙂
