### ISSUE TITLE
Add public method of Drag.filterDragElements to d.ts file

### ISSUE THREAD

**Issue by Cyara-Andrew-Watson** [ThibaultJanBeyer/DragSelect#224]
At the moment when I look at the d.ts file for Dragselect, the Drag property is private:
```
declare class DragSelect<E extends DSInputElement = DSInputElement> {
	// snip
	private Drag;
	// etc
}
```

As such, in order to use the documented override for drag behavior: https://dragselect.com/docs/API/Overrides#drag

I need to break out of the type system, so that I can constrain the drag movement to be purely vertical like so:

```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
;(ds as any).Drag.filterDragElements = (x: any) => {
	x.direction.x = 0 // By setting the drag x direction to 0, it will never move in the x direction, thus only vertical dragging
	return x
}
```

The code lists filterDragElements as a publicly exposed method, while the web documentation has it as internal, and the d.ts file has it as private.  
My concern is that, at the moment, the interface of the function could change in a future version, and I would not know about it until the functionality broke.  If this method could be added to the interface on the d.ts file, that would be awesome.

**Comment by ThibaultJanBeyer** [comment]
Even tho' the support to these internal overrides is limited indeed, I don't see too much harm in exposing the class, so will do that :)

**Comment by ThibaultJanBeyer** [comment]
Done in 3.0.6 ✅ 

However, I think a better feature request here would be to have an option to restrict the drag to a certain direction, [similar to dNd restrictions](https://thibaultjanbeyer.github.io/dragNdrop/#twoc) thanks for the idea, will add it to the roadmap 🗺️
