### ISSUE TITLE
dragging in a scrollable div

### ISSUE THREAD

**Issue by sharperpixels** [ThibaultJanBeyer/DragSelect#23]
Great library and thank you for building it!

I'm having an issue with drag selecting within a scrollable div. Safari 11 will scroll the div when you get to the edge, but the selected divs that get scrolled out of the parents viewport become unselected.

Chrome 65 doesn't scroll when I reach the edge of the parent div and neither does Firefox 57 so I can't test them.

Any ideas?

**Comment by sharperpixels** [comment]
Hi ThibaultJanBeyer,

Thanks for making the CodePen as an example. I found out that if you don't set an "area" for the DragSelect, then scrolling beyond the div's viewport will cause the issue.

I've set the "area" on the DragSelect in my html and it's working as it should.

Thanks

**Comment by ThibaultJanBeyer** [comment]
That is great to hear 👍 . I’m glad I could help. Now don’t forget to star this repo if you like the tool :)
Thank you
