### ISSUE TITLE
keyup event doe not bubbling up when selection is performed with selection rect

### ISSUE THREAD

**Issue by romgere** [ThibaultJanBeyer/DragSelect#235]
**Describe the bug**

keyup event is not correctly bubbling up to parent when a selection (single or multiple element) is made by dragging selection zone with the mouse.

No issue when selecting item(s) with single click. 

**To Reproduce**
1. Go to https://codepen.io/romgere/pen/RwzzgJo
2. Click on an item
3. press some keys, notice console log line for every key pressed
4. Select on or more item by using mouse
5.  press some keys, notice there no console log key pressed
6. Goto 2, notice it only appens when selecting item with mouse selection

**Expected behavior**
`keyup` event to bubble up to parent on both cases

**Code Example**
https://codepen.io/romgere/pen/RwzzgJo

**Screenshots**
![keyevent](https://github.com/user-attachments/assets/284a6030-f287-48ff-a5c4-419896a18c7a)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: last

**Smartphone (please complete the following information):**
Didn't test

**Additional context**
I'm could probably address a PR if you're able to give me some clues on what's happening here ...

**Comment by romgere** [comment]
Hum, I looked into the code, and I didn't find any reason this is happening.
I'm wondering if it could because, when drawing the blue rect for the selection, adding & removing it to the DOM make the focus "lost". So focus is given back to document itself or a parent element, so no keyup event on `#container`in this case 🤔 
What do you think ?

**Comment by romgere** [comment]
I was able to confirm the theory above, does not looks related to the library itself.
Sorry for the false positive

**Comment by ThibaultJanBeyer** [comment]
No worries @romgere ! Happy to see you using the library anyways, hope it went smooth from then on 🤗
