### ISSUE TITLE
Tap-drag for touch devices

### ISSUE THREAD

**Issue by psalmody** [ThibaultJanBeyer/DragSelect#28]
**Is your feature request related to a problem? Please describe.**
Touch functionality is non-existent

**Describe the solution you'd like**
Tap and drag would work exactly like click-drag

**Comment by ThibaultJanBeyer** [comment]
Hey @psalmody thanks for creating that issue.
Indeed that seems to be a missing functionality.
Do you feel confident enough to implement it and create a pull request?
Thank you! 💯

**Comment by psalmody** [comment]
@thibaultjanbeyer looking at the source, I think it's just a matter of adding event listeners for touch events where mouse events are happening?

I'll give it a shot but I'm not sure if I'll have a chance to do it in the next week or two.

**Comment by ThibaultJanBeyer** [comment]
Awesome, that would be flawless, thank you! 👍 
I’ll assign it to you, let me know if you need any help =)
