### ISSUE TITLE
How avoid to deselect a selected element when clicking on it?

### ISSUE THREAD

**Issue by ciaoben** [ThibaultJanBeyer/DragSelect#31]
I need to insert right before an element in selected.

When I click on a selected element I need to avoid to "deselect" it under some circumstances.
How can I achieve this?

**Comment by ThibaultJanBeyer** [comment]
Hey Ciaoben, thanks for using the tool. I'm currently on my honeymoon and thus not able to look into this. That should be possible somehow. Worst case you could re-add the element on unselection. I'll be able to help you out in 3 weeks. Until then please have a look at the documentation and let me know if you found a workaround. Thank you 😊

**Comment by ThibaultJanBeyer** [comment]
Had a quick look at the documentation. I think what you are looking for is the `multiSelectMode` attribute. Set it to `true` and multiselection will be the default. 

If you want to completely remove elements from the selectable list after selection, you can use a combination of `removeSelectables` and `onElementSelect`. Like so (pseudo code, not tested): `onElementSelect: function(element) { ds.removeSelectables(element); }`
Then, as soon as an element is selected it gets removed from the selectable elements. 

If you want this to happen only *after* a full selection, then use the regular callback maybe like this (pseudocode, untested):
`callback: function(elements) { this.removeSelectables(elements); }`

@ciaoben Does that solve your question? Don't forget to star the repo and follow me if you like it :)
Let me know if you need further help
