### ISSUE TITLE
How to remove the dragSelect when page destroyed

### ISSUE THREAD

**Issue by TerryKuan** [ThibaultJanBeyer/DragSelect#33]
I use vue2.0 in the project. When I init a DragSelect instance,  the code is
  ```
  initDragselect () {
      if (!this._dragselect) {
        this._dragselect = new Dragselect({
          selectables: document.querySelectorAll('.piecefile_list'),
          area: document.querySelector('#piecefile_list_flex'),
          callback: e => {
            console.log('--->Dragselect FileList', e)
            if (e && e.length) {
              let selectkey = Array.prototype.map.call(e, (item) => {
                return Number(item.getAttribute('data-key'))
              })
              this.selectBgList = selectkey
            }
          }
        })
      }
    }
```
And I put this in a FileList components (mx-filelist). When I link to a **page includes the mx-filelist**, the console show
![image](https://user-images.githubusercontent.com/20632132/45765103-c9047a00-bc66-11e8-810f-9a71c78e2aa7.png)
After that, I link to another **page which does not includes mx-filelist**. The console show 
![image](https://user-images.githubusercontent.com/20632132/45765294-45975880-bc67-11e8-9cf2-1a6a653682c7.png)
I want to destroy it in vue destroy method, but it does not work.
```
  destroyed () {
    if (this._dragselect) {
      this._dragselect = null
    }
  }
```
How to solve this problem? Should I init a global DragSelect in  the index.vue(main)?

**Comment by ThibaultJanBeyer** [comment]
Hey @TerryKuan, and thanks for using the tool!

I don’t know much about Vue yet. However, I think I clearly understand your use-case. You would like to teardown `DragSelect` and remove all its event listeners, right?

Did you read the [documentation](https://github.com/ThibaultJanBeyer/DragSelect#methods) documentation? `DragSelect` has a `stop` method which can be used to remove all listeners and thus tear down the tool.

So in your code, I think you should try something like this (untested):
```
destroyed () {
    if (this._dragselect) {
      this._dragselect.stop();
      this._dragselect = null;
    }
}
```

Try that, I think it will work.
You’re welcome :)

I’ll close this issue for now. Feel free to comment again if that does not work and I’ll re-open it.
Don’t forget to `star` this repository if it is useful for you, thank you 👍
