### ISSUE TITLE
1.8.1 on npm but not on github

### ISSUE THREAD

**Issue by walterra** [ThibaultJanBeyer/DragSelect#34]
First, thanks for doing DragSelect, it's a great library!

Just a note and for lack of a better place filing an issue here:

I just noticed by coincidence by looking at the code on master there is a `setSelectables` method in version `1.8.1` but couldn't find the version when I looked at https://github.com/ThibaultJanBeyer/DragSelect/releases — so I thought it wasn't released yet and in the works. But then I saw it's already released on npm, so it's there and I was able to upgrade via `package.json`. Might be worth adding it to the github release page so others don't miss it :).

**Comment by ThibaultJanBeyer** [comment]
Thanks for the kind words and for using the tool!
I forgot about it. Thank you for the reminder :)
