### ISSUE TITLE
1.11.3 .stop() fires callback

### ISSUE THREAD

**Issue by Martin-Eckleben** [ThibaultJanBeyer/DragSelect#37]
Im using npm module dragselect 1.11.3

When .stop() ing the dragselect in the callback js dies in an endless loop:
https://codepen.io/Exxenmann/pen/eoJPNZ

Im trying for example to end "selection mode" (.stop() ing it) after the selection is complete.

Ill try to solve it starting in about six hours (after work) and file a pull request if I can.

Am I just stupid / trying something oviously wrong or is this really a bug?

**Comment by Exxenmann** [comment]
.stop() seems to fire callback which is described as "fired once the user releases the mouse. (elements) = selected nodes."

On first sight I think this is not intuitive/right?
Am I missing something?

**Comment by Exxenmann** [comment]
For readers whith same issue until PR is solved:
Should be solved in pull request #39

**Comment by ThibaultJanBeyer** [comment]
Yup, makes sense, since `stop` will call `reset` which itself triggers the callback. Definitively a bug! Thanks
