### ISSUE TITLE
1.11.3 .stop() does not cancel all functionality

### ISSUE THREAD

**Issue by Martin-Eckleben** [ThibaultJanBeyer/DragSelect#38]
If I call .stop() all functionality is gone as it should be.
But if I afterwards click a selectable element all functionality is "restored".

https://codepen.io/Exxenmann/pen/gyPVaW

Will file a pull request if/when I solve it.

**Comment by ThibaultJanBeyer** [comment]
Hey there Exxenmann and thanks for reporting! I would be very happy on a PR. Thank you.

**Comment by Exxenmann** [comment]
Sorry yesterday was too busy but today starts the weekend and I will hopefully be able to solve it.

"Thank you."
No thank you for this great library :)

**Comment by Exxenmann** [comment]
For readers whith same issue until PR is solved:
Should be solved in pull request #39

**Comment by ThibaultJanBeyer** [comment]
I had a look at it. As it seems there is logic missing in the `stop` method to remove the `click` event listener on the `_addSelectable`. Nice catch!
