### ISSUE TITLE
Select all items between two Shift- clicks

### ISSUE THREAD

**Issue by nastakhov** [ThibaultJanBeyer/DragSelect#48]
Thank you for the wonderful library!

Can you please provide me direction with how to tackle my problem. 

I need to be able to select all items between two of them - first one and last. 
Scenario: user shift-clicks on first item, then shift-clicks on last and all items in between become selected.

Maybe this is already implemented and I'm missing something.

**Comment by ThibaultJanBeyer** [comment]
Hi @nastakhov and thank you for using the library!

No that's not possible, currently the user would have to click and drag with the mouse while holding shift.

I think this would be difficult from the library to do. I can keep this as an investigation ticket and have a look if I've time. If you want you can also give it a try of course?

For now you can just use the [`onElementSelect`](https://thibaultjanbeyer.github.io/DragSelect/DragSelect.html) callback, check wether the multiselection key was pressed and then select the elements between yourself via [`addSelection()`](https://thibaultjanbeyer.github.io/DragSelect/DragSelect.html#addSelection)

**Comment by ThibaultJanBeyer** [comment]
This request was open for >10 months and did not get any substantial amount of votes. As mentioned you're able to calculate it yourself. So I'm closing it for now. Feel free to still contribute and add that functionality as an addition to the project as I'm not opposed to it.

**Comment by gwennlbh** [comment]
If people are looking for a lib that supports this, I ended up switching to [Viselect, that supports it](https://simonwep.github.io/viselect/pages/quickstart.html#configuration:~:text=//-,Range%20selection,-.) after implementing by hand
