### ISSUE TITLE
Option to pass two-finger touch gestures through to browser for scrolling

### ISSUE THREAD

**Issue by JonFabritius** [ThibaultJanBeyer/DragSelect#53]
**Is your feature request related to a problem? Please describe.**
When an area containg selectables exceeds the viewport, no method for scrolling the view without selecting exists on touch devices. Using one finger to scroll the view results in elements being selected.

**Describe the solution you'd like**
Google Maps embeds have solved this by having a two finger drag for scrolling the map area. In their case the default one finger scroll would render a page unscrollable, if a map view filled the screen. Since two fingers already scroll (on iOS atleast) similarly to one finger, an option to 'ignore two finger drags' would simply let the browser handle them as usual.

**Describe alternatives you've considered**
I've dabbled with recognizing two finger events, but it requires a bif of effort, since even the slightest time delay between finger 1 and 2 triggers *both* events. I can go around this by adding an 'activate selection mode' item for touch screen users (as a button, or a thing you hold down temporarily with another finger to toggle behaviour).

**Comment by lcollazo-ilovepdf** [comment]
A possible (and easy) solution could be adding a flag (i.e called multiSelectToggle that defaults to true) and in the **_handleSelection** function take into account the value of this variable.

**Comment by ThibaultJanBeyer** [comment]
Hi @JonFabritius thanks for your input and thanks for using DragSelect!

I understand the problem but I'm not sure about the proposed solutions. As you wrote yourself, the two finger solution is not ideal.
Adding a button to "enable selection" sounds like a very good solution. This however is not the responsability of DragSelect in my opinion and should not be part of the tool itself. It is something for engineers to add themselves.
I.e. you could add that button and only enable DragSelect functionality then the button is pressed.

I'll close this issue for now unless we have a better solution. Feel free to comment when you have a nice one or open. I'll also think about this. :+1:
