### ISSUE TITLE
Is it possible to change the color of drag selection from blue to red?

### ISSUE THREAD

**Issue by born2net** [ThibaultJanBeyer/DragSelect#54]
Is it possible to change the color of drag selection from blue to red?
Thanks

Sean

**Comment by ThibaultJanBeyer** [comment]
Hi there Sean and thanks for using DragSelect!

Yes of course that is possible. It is as simple as using CSS.
- The selection has the `.ds-selector` Class ([as written in the docs](https://github.com/ThibaultJanBeyer/DragSelect#classes)) which you can style however you want.

Have Fun!

**Comment by born2net** [comment]
THANKS, Love your project!
