### ISSUE TITLE
Allow alternative behavior for MultiSelectMode

### ISSUE THREAD

**Issue by lcollazo-ilovepdf** [ThibaultJanBeyer/DragSelect#58]
**Is your feature request related to a problem? Please describe.**
If you have already items selected and you press Shift key to enter multiSelect mode, I want to add new selected elements without deselecting the ones that are already selected.
Currently programmed behavior in the library will deselect items if in multiSelect mode if they are selected. This behavior is the same that happens when you are with a Mac OS in the desktop and selecting the icons in the desktop.
Unlike Windows, which does the opposite.

**Describe the solution you'd like**
It would be great to have a flag/option to control the behavior of whether you want to deselect or still have them selected if the selection rectangle of the library hovers over an already selected item in multiSelect mode.
Or have a callback function that allows you to control this behavior in real time.
I am open to suggestions in the way this can be implemented.

**Describe alternatives you've considered**
I have yet to explore a way to implement this behavior already with the provided public API of the library but it is likely that the end implementation will be somewhat dirty or confusing to achieve it.

**Comment by lcollazo-ilovepdf** [comment]
A possible (and easy) solution could be adding a flag (i.e called multiSelectToggle that defaults to true) and in the _handleSelection function take into account the value of this variable.

**Comment by ThibaultJanBeyer** [comment]
Hi @lcollazo-ilovepdf thanks for this well described feature request and for using the tool!

Just to unblock you: It's not perfect (as it will keep it as soon as you touch it) but this should work:
```JavaScript
const ds = new DragSelect({
  ...
  onElementUnselect: function(el) {
    if(this._multiSelectKeyPressed)
      this.addSelection(el)
  }
 ...
});
``` 
Let me know if that un-blocked you.

For a generic solution, I like your idea with the flag (multiSelectToggle). If you want, go ahead and create a PR for this, it would be a good addition and much apretiated! :+1:
