### ISSUE TITLE
Dragselect2.0.0 error with npm start

### ISSUE THREAD

**Issue by Xumochuan** [ThibaultJanBeyer/DragSelect#72]
**Describe the bug**
Thanks for your great lib. 
I updated package to v2.0.0 today, and run npm start.
I got this issue.

Hope your kind contact
Thanks

**Screenshots**
![image](https://user-images.githubusercontent.com/47884397/103756867-ebdf1600-504a-11eb-92ed-72a4fe63c9e8.png)

**Env**
 - Angular v11
 - Node 14.15.4

**Comment by ThibaultJanBeyer** [comment]
Hi Xumochuan! Thanks for opening the issue.
Hmm, that is pretty interesting. Let me try to reproduce it.

**Comment by ThibaultJanBeyer** [comment]
I was able to reproduce the issue.
It had to do with residue in the `gitignore`.
It should be fixed in `v2.0.1` please check

**Comment by ThibaultJanBeyer** [comment]
Let me know if it's not resolved, we can re-open
