### ISSUE TITLE
keep aspect

### ISSUE THREAD

**Issue by plotpoi** [ThibaultJanBeyer/DragSelect#75]
Thank you for the wonderful project.
Is it possible to maintain the aspect ratio by grouping?

Specifically, when the edge is crossed, all items in the group will have a distance of 0 from the edge.
<img width="462" alt="スクリーンショット 2021-01-07 23 39 15" src="https://user-images.githubusercontent.com/48230911/103905439-f4fede80-5141-11eb-86b7-26fc84d81201.png">
→
current
<img width="322" alt="スクリーンショット 2021-01-07 23 39 20" src="https://user-images.githubusercontent.com/48230911/103905457-fa5c2900-5141-11eb-9dcb-aa2496431329.png">

It is my ideal to be kept like this.
<img width="323" alt="スクリーンショット 2021-01-07 23 39 32" src="https://user-images.githubusercontent.com/48230911/103905493-06e08180-5142-11eb-8242-726d779bcc2e.png">

I would appreciate it if you could consider it.

**Comment by ThibaultJanBeyer** [comment]
Hi @plotpoi thank you for using the tool and sharing your wish :)
I'm opening this for vote. Please share your use-case.
If you want it faster, feel free to try it immediately and open a pull request with your changes!

**Comment by ThibaultJanBeyer** [comment]
This issue is 1 year old and got 0 votes. Hence we'll not focus on it. Feel free to re-open if you want to work on it :)
