### ISSUE TITLE
Expect to be able to set the default selected value.

### ISSUE THREAD

**Issue by littlePig-zzf** [ThibaultJanBeyer/DragSelect#76]
**Describe the bug**
I have a appointment time requirements，In addition to the addition of the ability to edit, currently the component does not appear to be able to set the default selected value，So don't know how to fix the default.

**To Reproduce**
1. New selection for appointment time.
2. View booking times for details.
3. Edit Appointment Time.
4. Unable to set the default value.

**Expected behavior**
Expect to be able to set the default selected value.

**Comment by ThibaultJanBeyer** [comment]
Dear @littlePig-zzf I believe you opened your issue on the wrong library? DragSelect is a selection + drag-drop library. It has nothing to do with calendars, appointments or time. I'm closing this, if you can provide information that your bug is related to DragSelect, please let me know.
