### ISSUE TITLE
TS types are out of date (still on version 1.13.1)

### ISSUE THREAD

**Issue by Marcel50506** [ThibaultJanBeyer/DragSelect#78]
There is no Types information available for the newest version of your library. When npm installing '@types/dragselect', I get types of version 1.13.1, while the library is already at 2.0.2.

The types definitions (of 1.13.1) are located here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dragselect

I'm not sure if you are maintaining this, or if someone else is, but I wanted to post this feedback.

**Comment by ThibaultJanBeyer** [comment]
Hi, looks like those types were created by someone else, I did not know that they exist. If you look at the project you linked, you can see that they were created by IceCreamYou. Greetz
