### ISSUE TITLE
What is the equivalent to .break() in v2?

### ISSUE THREAD

**Issue by hazemelgamal** [ThibaultJanBeyer/DragSelect#80]
.break() was removed in v2. It used to disable the execution of the upcoming code without tearing down the functionality.

This was a very important method when you want to disable the dragselect functionality temporarily,  what is the equivalent method in v2 to achieve the same thing?

Thank you!

**Comment by ThibaultJanBeyer** [comment]
Hi @hazemelgamal !
Thanks so much for using DragSelect 💪 

I was not aware that it's even used/useful and it was complicating the migration, but does not mean we can't have it :)

Could you please share your exact use-case and where you used the `.break()` functionality, then I can have a closer look whether you can use something else or whether it makes sense to add break back again.

Thank you!

**Comment by hazemelgamal** [comment]
@ThibaultJanBeyer Thanks for the quick response! 

.break() was extremely important that removing it is preventing me from upgrading to v2.

The use case is simple, I'm using another library to drag and drop the same items that can be selected by DragSelect. When an item is being dragged/moved by the other library, I was using the break() method to temporarily disable DragSelect. 

Of course the new "Draggability" feature can't replace the other library, it's different and limited.

I appreciate your support!

**Comment by ThibaultJanBeyer** [comment]
Hi thanks for the quick answer. The aim is to replace the other library in the long run. Would you mind sharing the features that you're missing or in what sense it's limited?

**Comment by hazemelgamal** [comment]
The other library is https://gridstackjs.com. I don't think it's a good idea to assume that you can replace other libraries, it limits DragSelect and there's no way you can develop every feature from every other library. Focus on the core of DragSelect, that's just my two cents. 

I would appreciate if you can bring back the break method. Thanks for your support!

**Comment by ThibaultJanBeyer** [comment]
It was a request that had a lot up-votes and people wanting to have a combination of selection and drag and drop (DND) I do think it's possible to have both in one and I also believe that there is a benefit having an integrated solution. 
Have you tried the integrated DND solution? Could you please be more specific on what feature gridstack offers that you would need in order to use the integrated solution?

We should add back a possibility that you can use your own DND (not necessarily the ugly .break 😅), as you said, short term we won't be able to replicate everything. If you feel confident enough, please go ahead and create a PR to allow this. This addition would be very much appreciated 👍

**Comment by ThibaultJanBeyer** [comment]
Hi, @hazemelgamal I'm working on this now and trying to understand how you used to use both, DragSelect and GridStack. I'm trying to use both together as well to understand how that would work. Would you be so kind to send me an example with DragSelect v1?

Could something like this work?:
```
ds.subscribe('Interaction:start', ({ isDragging }) => isDragging && ds.stop(false, false));
grid.on('dragstop', () => ds.start());
```
While `ds` is the instance of `DragSelect` and `grid` the instance of `GridStack`.
You could also not care about isDragging and use `.stop` whenever you want 🤔 

Ideally, I'd want to add a setting like "customDnD" that has the exact behaviour of the tool you need to have to integrate your own drag and drop solution, tool.

But for that, I really need to understand exactly how it is used to be able to come up with an improvement in DragSelect that suits 3rd party integration needs.

Thank you!

**Comment by ThibaultJanBeyer** [comment]
Issues a PR that Adds some utilities to support this. Tried out with the library you linked and the following set-up:

```
  const items = [
    {content: 'my first widget'}, // will default to location (0,0) and 1x1
    {w: 2, content: 'another longer widget!'} // will be placed next at (1,0) and 2x1
  ];
  const grid = GridStack.init();
  grid.load(items);

  const ds = new DragSelect({
    selectables: document.querySelectorAll('.grid-stack-item-content'),
    keyboardDrag: false
  })
  ds.subscribe('predragstart', ({ isDragging }) => isDragging && ds.stop(false, false))
  grid.on('dragstop', () => ds.start());
```

Seems to work flawlessly.
Let me know what you think :)

**Comment by ThibaultJanBeyer** [comment]
Also re-added break. While it's not what you need it does potentially help people building stuff on top of DragSelect.
