### ISSUE TITLE
draggability doesn't disable dragKeys

### ISSUE THREAD

**Issue by Fu7ure** [ThibaultJanBeyer/DragSelect#83]
First things first: Thanks for this sweet plugin!

**Describe the bug**
I'm working on an application, where I've implemented DragSelect using `draggability: false`. Since I now want to use the arrow keys for other events, I noticed that the arrow keys still move the elements around and I need to additionally set `dragKeys: { up: [], down: [], left: [], right: [] }` to prevent this. Since I think most use-cases where draggability is set to false don't want their elements to move **at all**, I would consider this unexpected behaviour.

**To Reproduce**
1. Set `draggability: false` when initializing DragSelect
2. Press the arrow buttons
3. See the elements move around

**Expected behavior**
I would expect dragKeys to either default to `{ up: [], down: [], left: [], right: [] }` or be disabled entirely when draggabilty is set to false.

**Desktop**
 - OS: Manjaro Linux
 - Browser: Chrome, Firefox, probably all

**Comment by ThibaultJanBeyer** [comment]
Hi Fu7ure thanks a lot for raising this and using the tool! That is indeed a bug. If you feel confident a PR to fix this would be very much appreciated :)

**Comment by Fu7ure** [comment]
Hi Thibault,
thanks for the quick response!
No problem. But since I'm quite stressed right now because of exams and moving out, It could take a bit.
If you (or someone else) didn't fix it till I got some time at hand, I'll gladly do it.

Cheers!

**Comment by ThibaultJanBeyer** [comment]
Will be available in next version
