### ISSUE TITLE
Dragselect works locally but not on deployed versions. 

### ISSUE THREAD

**Issue by aaditya9** [ThibaultJanBeyer/DragSelect#86]
**Describe the bug**
I am using Dragselect 1.15.1.  Can see warnings Dragselect is deprecated on deployed versions, but locally can not see any warnings and it works fine.
I am open to upgrading my dragselect version but would like to get this issue resolved beforehand.

**Expected behaviour**
It should work on both local and production or not work at all.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version : 90.0.4430.72 (Official Build) (x86_64)

**Comment by ThibaultJanBeyer** [comment]
Hi @aaditya9 thanks a lot for using the tool 🤗 

DragSelect 1.15.1 is a lot of versions behind. We're at version 2+ already

Unfortunately, I'm not able to give you any support for this old version.
Please upgrade, feel free to let me know if you need any help with your upgrade.

Have a lovely day =)
