### ISSUE TITLE
Methods: ds.removeSelectables doesn't remove the seletable elements

### ISSUE THREAD

**Issue by lchtao26** [ThibaultJanBeyer/DragSelect#90]
Hi, Thibault, really appreciate your work on dragselect, it's easy to learn and use! As I'm using it on my project, I found the `ds.removeSelectables` doesn't work as I expect.

**Describe the bug**
ds.removeSelectables doesn't remove the seletable elements

**To Reproduce**
[codepen  demo](https://codepen.io/lchtao26/pen/dyvRjeq?editors=1111)

1. Init a ds instance, add some selectables
2. create a button, add click handler, to execute follow process
```
  const prevSelectables = ds.getSelectables();
  
  ds.removeSelectables(prevSelectables);

  const removedSelectables = ds.getSelectables();

  // It turns out `prev` and `removed` length is the same, dosen't remove any selectable elements, it only remove the selected elements.
  console.log('prev', prevSelectables)
  console.log('removed', removedSelectables)
  console.log(prevSelectables.length === removedSelectables.length);
```

**Expected behavior**
ds.removeSelectables(elements) should remove the elements correctly

**Additional context**
As searching for the source code, I find the `removeSelectables` methods in `DragSelect.js`
https://github.com/ThibaultJanBeyer/DragSelect/blob/8c77a327e579d2ee99b559fc37b4d04c06909651/src/DragSelect.js#L433-L437
```
  removeSelectables(elements, removeFromSelection = false) {
    this.SelectedSet.clear()  // NOTE: As I expected, it should be `this.SelectableSet.clear()
    if (removeFromSelection) this.SelectedSet.clear()
    return elements
  }
```

I'm not sure whether the `this.SelectedSet.clear()` is the source of bug, it doesn't meet my expectation.

**Comment by ThibaultJanBeyer** [comment]
Hi @Ichtao26 and thanks for the kind words!

You're right, it seems that there is a bug. That code does not seem correct: 
- First, it should be selectableset, as you mentioned. 
- Second it should probably not be clear all as you don't want to remove all of them but only the elements you pass in.

I'm currently super busy so I'd be happy if you'd have a try to fix it and I can review the PR.
Otherwise, I'll do it as soon as I've some free time again, which might take a while.

Thank you for raising this and this super clear issue report

**Comment by lchtao26** [comment]
Glad to receive your feedback, I'll fork and try to submit a PR

**Comment by ThibaultJanBeyer** [comment]
Your changes are live now in version `2.0.3`. You've joined the club of contributors and have been mentioned in the changelog. This means whenever we get [donations](https://github.com/ThibaultJanBeyer/DragSelect#supporters), those are split among contributors.

But don't get your hopes too high, unfortunately, no one donates anything for open source ever, we have like 6€ total, which is somewhat demotivating :'(

Anyways, thanks a lot!!

**Comment by lchtao26** [comment]
Whether there is a return or not, it is enjoyable to do something for open-source project. It's my pleasure to contribute to the new version!
