### ISSUE TITLE
Please provide an option to clean up the DOM when stop() is called.

### ISSUE THREAD

**Issue by diomedtmc** [ThibaultJanBeyer/DragSelect#94]
**Is your feature request related to a problem? Please describe.**
Cannot tear down the selectable area with a React hook lifecycle.  (ie - unmount).

**Describe the solution you'd like**
I'd like to be able to call a DragSelect (stop) method, and have it clean up the DOM for me, rather than me do it myself.

**Describe alternatives you've considered**
I query the DOM for the actual DragSelect ds-selector-area, and remove it myself on hook unmount.  I tried passing into 'true' for remove, but it doesn't seem to clean-up the DOM.  I can also try a singleton approach using start/stop as well.  However, since drag-select places itself at the root level of the document, this becomes very hard to componentize.

**Additional context**
My work is generally within React, and is component focused.  Also, the fact stop is not tearing down the DOM correctly might just be an outright bug?

**Comment by ThibaultJanBeyer** [comment]
Hi again 👋 

Yes, you're right we probably forgot to also remove the elements on teardown. The `stop` only handles even listeners I think!
Great finding.

Same here, would you want to give it a try? That'd be very much appreciated!

Either that the `stop` method also removes DOM elements and the `start` one also creates them? Or a separate teardown.

Thank you @diomedtmc 🤗

**Comment by diomedtmc** [comment]
Hi @ThibaultJanBeyer ,

I can probably take a closer look at this in a couple of days if you want me to.

😄

**Comment by ThibaultJanBeyer** [comment]
done :)
