### ISSUE TITLE
Console print on keypress

### ISSUE THREAD

**Issue by megasanjay** [ThibaultJanBeyer/DragSelect#99]
**Describe the bug**
With the latest version of DragSelect keypresses are being automatically logged to the console. 

**To Reproduce**
1. Press any button on the latest version of DragSelect from npm

**Expected behavior**
No console log on regular keypresses

**Screenshots**
![image](https://user-images.githubusercontent.com/21206996/125131237-3f442680-e0b7-11eb-837c-29ddb5f543db.png)

**Desktop (please complete the following information):**
 - OS: [ Any ]
 - Browser [ Electron ]

**Additional context**
v 2.0.2 did not have this console print

**Comment by ThibaultJanBeyer** [comment]
Hello there, thank you for using the tool!

Yes this is a leftover in the non-minified version, removed it here: https://github.com/ThibaultJanBeyer/DragSelect/pull/101/files#diff-56116c5ad8b7cae154647277938ee084e17117f50e56ab280e2140e304bf543dL99

I'd generally suggest either using the minified version or minifying your build for production.

As it will be gone in the next version soonish, closing it already
